//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewType.Seeker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewType.Seeker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SELECT
        ///    b.name as &quot;tableName&quot;,
        ///    a.name as &quot;columnName&quot;,
        ///    c.name as &quot;type&quot;,
        ///    a.column_id as &quot;order&quot;,
        ///    a.max_length as &quot;length&quot;,
        ///    a.precision,
        ///    a.scale,
        ///    case
        ///        when a.is_nullable = 0
        ///        then &apos;×&apos;
        ///        else &apos;○&apos;
        ///    end as &quot;boolnull&quot;,
        ///    case
        ///        when a.is_identity = 0
        ///        then &apos;×&apos;
        ///        else &apos;○&apos;
        ///    end as &quot;オートナンバー&quot;,
        ///    case
        ///        when a.default_object_id = 0
        ///        then &apos;×&apos;
        ///        else d.definition
        ///    end as &apos;デフォルト値&apos;,
        ///    case
        ///     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT name FROM sys.databases ORDER BY database_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataBases {
            get {
                return ResourceManager.GetString("DataBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DataTable_8468 {
            get {
                object obj = ResourceManager.GetObject("DataTable_8468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   SQLServerとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLServerとの接続に失敗しました。既存の設定を使用して再接続します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続情報が未設定です。設定画面を開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLServerとの接続が開かれていません。設定画面から接続情報を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLServerとの接続を切断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLServerとの接続に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message9 {
            get {
                return ResourceManager.GetString("Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SSRICON {
            get {
                object obj = ResourceManager.GetObject("SSRICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   select o.name as Name, i.Rows as &apos;Rows&apos;, count(s.column_id) as Columns from sysindexes i, sysobjects o inner join sys.columns s on s.object_id = o.id where o.xtype = &apos;U&apos; and o.id = i.id and i.indid &lt; 2 and o.name &lt;&gt; &apos;dtproperties&apos; group by o.name, i.Rows order by o.name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon VSNETWebServiceDynamicDiscovery_8215 {
            get {
                object obj = ResourceManager.GetObject("VSNETWebServiceDynamicDiscovery_8215", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
